services:
  mame:
    image: lscr.io/linuxserver/mame
    container_name: mame
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${VOL_MAME_CONFIG:-~/container-data}/container-mounts/mame/config:/config
      - ${VOL_MAME_EXTRAS:-~/container-data}/container-mounts/secure-webtop/downloads/mame/MAME 0.276 EXTRAs:/mame
      - ${VOL_MAME_ROMS:-~/container-data}/container-mounts/secure-webtop/downloads/mame/MAME 0.279 ROMs (merged):/mame/roms:ro
      - ${VOL_MAME_CHDS:-~/container-data}/container-mounts/secure-webtop/downloads/mame/MAME 0.279 CHDs (merged):/mame/chds:ro
    shm_size: "1gb"
    networks:
      - mame-net
    labels:
      # For homepage
      - homepage.group=Desktop Apps
      - homepage.name=MAME
      - homepage.weight=110
      - homepage.icon=/icons/mame.ico
      - homepage.href=https://mame.${TS_DOMAIN}
    healthcheck:
      test: 'curl --fail http://localhost:3000/manifest.json 2>/dev/null | grep -o "MAME" || exit 1'
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    restart: on-failure
  ts:
    container_name: mame-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=mame
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - mame-net
    depends_on:
      mame:
        condition: service_healthy
    restart: on-failure
networks:
  mame-net:
