services:
  kanboard:
    container_name: kanboard
    image: kanboard/kanboard
    volumes:
      - ${VOL_KANBOARD_DATA:-~/container-data}/container-mounts/kanboard/data:/var/www/app/data
      - ${VOL_KANBOARD_PLUGINS:-~/container-data}/container-mounts/kanboard/plugins:/var/www/app/plugins
      - ${VOL_KANBOARD_NGINX_SSL:-~/container-data}/container-mounts/kanboard/nginx_ssl:/etc/nginx/ssl
    healthcheck:
      test: curl --fail http://localhost/login | grep "Username" || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - kanboard-net
    labels:
      # For homepage
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=KanBoard
      - homepage.weight=10
      - homepage.icon=/dashboard-icons/svg/kanboard.svg
      - homepage.href=https://kanboard.${TS_DOMAIN}
    restart: on-failure
  ts:
    container_name: kanboard-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=kanboard
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ${TS_STATE_HOST_DIR}:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - kanboard-net
    depends_on:
      kanboard:
        condition: service_healthy
    restart: on-failure
networks:
  kanboard-net:
