# https://hub.docker.com/r/codercom/code-server
# https://github.com/coder/code-server
# https://tailscale.com/kb/1166/vscode-ipad Not really used, but some interesting info.
services:
  code:
    container_name: code
    image: codercom/code-server
    volumes:
      - ${VOL_CODE_HOME:-~/container-data}/container-mounts/code/home:/home/coder
    environment:
      # Executable scripts placed in this folder will run when the container starts.
      # They can be used for setting up dependencies and such that cannot "just live in $HOME"
      - ENTRYPOINTD=/home/coder/code-entrypoint-scripts
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - code-net
    labels:
      # For homepage
      - homepage.group=My Stuff
      - homepage.name=code
      - homepage.weight=60
      - homepage.icon=/dashboard-icons/svg/code.svg
      - homepage.href=https://code.${TS_DOMAIN}
    restart: on-failure
  ts:
    container_name: code-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=code
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - code-net
    depends_on:
      code:
        condition: service_healthy
    restart: on-failure
networks:
  code-net:
