services:
  browser:
    # https://docs.linuxserver.io/images/docker-vivaldi/
    image: lscr.io/linuxserver/ungoogled-chromium
    container_name: browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC # No need to leak my timezone
      - SUBFOLDER=/ #optional
      - CHROME_CLI=--disable-gpu
      - TITLE=Browser #optional
    shm_size: "1gb" #optional
    network_mode: service:gluetun-browser
    labels:
      # For homepage
      - homepage.group=Desktop Apps
      - homepage.name=Browser
      - homepage.weight=100
      - homepage.icon=/dashboard-icons/svg/chromium.svg
      - homepage.href=https://browser.${TS_DOMAIN}
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -s https://ipinfo.io/ | grep -E -q 'Kansas|AT&T' && exit 1 || exit 0",
        ]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    restart: on-failure
    depends_on:
      gluetun-browser:
        condition: service_healthy
  gluetun-browser:
    # https://github.com/qdm12/gluetun
    image: qmcgaw/gluetun
    container_name: gluetun-browser
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    restart: on-failure
  ts:
    container_name: browser-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=browser
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    restart: on-failure
