services:
  starbound:
    container_name: starbound
    build:
      dockerfile: Dockerfile
    environment:
      STEAM_USER: ${STEAM_USER}
    volumes:
      - ${VOL_STARBOUND_STARBOUND:-~/container-data}/container-mounts/starbound/starbound:/starbound
    ports:
      - 21025:21025
    healthcheck:
      test: pgrep -f starbound_server || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    restart: on-failure
