services:
  seerr:
    # https://github.com/seerr-team/seerr
    image: ghcr.io/seerr-team/seerr
    container_name: seerr
    init: true
    environment:
      - TZ=America/Chicago
      - LOG_LEVEL=info
    volumes:
      - ${VOL_SEERR_CONFIG:-~/container-data}/container-mounts/seerr/config:/app/config
    labels:
      - homepage.group=My Stuff
      - homepage.name=Seerr
      - homepage.weight=46
      - homepage.icon=/dashboard-icons/svg/overseerr.svg
      - homepage.showstats=true
      - homepage.href=https://seerr.${TS_DOMAIN}
      - homepage.description=Media request management for Jellyfin.
    restart: on-failure
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - seerr-net
  ts:
    container_name: seerr-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=seerr
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - seerr-net
    depends_on:
      seerr:
        condition: service_healthy
    restart: on-failure
networks:
  seerr-net:
