services:
  netdata:
    container_name: netdata
    # Netdata will work but only partially as a non-root user?
    # It isn't clear what will or wont' work without root.
    # https://learn.netdata.cloud/docs/netdata-agent/installation/docker
    # This must be the ID of the Docker group.
    group_add:
      - ${DOCKER_GID:-985}
    image: netdata/netdata
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${VOL_NETDATA_NETDATACONFIG:-~/container-data}/container-mounts/netdata/netdataconfig:/etc/netdata
      - ${VOL_NETDATA_NETDATALIB:-~/container-data}/container-mounts/netdata/netdatalib:/var/lib/netdata
      - ${VOL_NETDATA_NETDATACACHE:-~/container-data}/container-mounts/netdata/netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - netdata-net
    # Note that netdata has a health check built into the Dockerfile, so no need to add it here.
    labels:
      # For homepage
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Netdata
      - homepage.weight=30
      - homepage.icon=/dashboard-icons/svg/netdata.svg
      - homepage.href=https://netdata.${TS_DOMAIN}
      - homepage.widget.type=netdata
      - homepage.widget.url=https://netdata.${TS_DOMAIN}
    restart: on-failure
  ts:
    container_name: netdata-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=netdata
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ${TS_STATE_HOST_DIR}:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - netdata-net
    depends_on:
      netdata:
        condition: service_healthy
    restart: on-failure
networks:
  netdata-net:
