services:
  gluetun:
    # https://github.com/qdm12/gluetun-wiki
    image: qmcgaw/gluetun
    container_name: recon-gluetun
    volumes:
      - ${VOL_RECON_GLUETUN:-~/container-data}/container-mounts/recon/gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Expose Sonarr and Radarr for Seerr (now in separate project)
      - 8989:8989
      - 7878:7878
    environment:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Gluetun VPN
      - homepage.icon=/dashboard-icons/svg/gluetun.svg
      - homepage.weight=10
      - homepage.showstats=true
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
      - homepage.widget.type=customapi
      - homepage.widget.refreshInterval=120000
      - homepage.widget.url=http://recon.${TS_DOMAIN}:8000/v1/vpn/status
      - homepage.widget.mappings[0].label=Status
      - homepage.widget.mappings[0].field=status
    restart: on-failure
  ts:
    container_name: recon-ts
    image: tailscale/tailscale
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - TS_HOSTNAME=recon
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ${TS_STATE_HOST_DIR}:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: on-failure
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
  flaresolverr:
    # https://github.com/FlareSolverr/FlareSolverr
    # DockerHub mirror flaresolverr/flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: recon-flaresolverr
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8191 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: recon-prowlarr
    volumes:
      - ${VOL_RECON_PROWLARR_CONFIG:-~/container-data}/container-mounts/recon/prowlarr/config:/config
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Prowlarr
      - homepage.weight=30
      - homepage.icon=/dashboard-icons/svg/prowlarr.svg
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:9696/
      - homepage.description=The Ultimate Indexer Manager.
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:9696 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: recon-qbittorrent
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    volumes:
      - ${VOL_RECON_QBITTORRENT_CONFIG:-~/container-data}/container-mounts/recon/qbittorrent/config:/config
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=qBittorrent
      - homepage.weight=20
      - homepage.icon=/dashboard-icons/svg/qbittorrent.svg
      - homepage.href=http://recon.${TS_DOMAIN}:8085/
      - homepage.description=an open-source software alternative to µTorrent.
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
      - homepage.widget.type=customapi
      - homepage.widget.refreshInterval=120000
      - homepage.widget.url=http://recon.${TS_DOMAIN}:8000/v1/publicip/ip
      - homepage.widget.mappings[0].label=Public IP
      - homepage.widget.mappings[0].field=public_ip
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8085 || exit 1"
      start_period: 30s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
  sonarr:
    image: lscr.io/linuxserver/sonarr
    volumes:
      - ${VOL_RECON_SONARR_CONFIG:-~/container-data}/container-mounts/recon/sonarr/config:/config
      - ${VOL_RECON_DATA_MEDIA_SERIES:-~/container-data}/container-mounts/recon/data/media/series:/tv
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    container_name: recon-sonarr
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Sonarr
      - homepage.weight=40
      - homepage.icon=/dashboard-icons/svg/sonarr.svg
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:8989/
      - homepage.description=Internet PVR for Usenet and Torrents.
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8989 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    network_mode: "service:gluetun"
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: recon-radarr
    volumes:
      - ${VOL_RECON_RADARR_CONFIG:-~/container-data}/container-mounts/recon/radarr/config:/config
      - ${VOL_RECON_DATA_MEDIA_MOVIES:-~/container-data}/container-mounts/recon/data/media/movies:/data
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Radarr
      - homepage.weight=50
      - homepage.icon=/dashboard-icons/svg/radarr.svg
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:7878/
      - homepage.description=See all your upcoming movies in one convenient location.
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:7878 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    network_mode: "service:gluetun"
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: recon-lidarr
    volumes:
      - ${VOL_RECON_LIDARR_CONFIG:-~/container-data}/container-mounts/recon/lidarr/config:/config
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Lidarr
      - homepage.weight=60
      - homepage.icon=/dashboard-icons/svg/lidarr.svg
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:8686/
      - homepage.description= Music collection manager for Usenet and BitTorrent users.
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8686 || exit 1"
      start_period: 30s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    network_mode: "service:gluetun"
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: recon-bazarr
    volumes:
      - ${VOL_RECON_BAZARR_CONFIG:-~/container-data}/container-mounts/recon/bazarr/config:/config
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Bazarr
      - homepage.weight=60
      - homepage.icon=/dashboard-icons/svg/bazarr.svg
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:6767/
      - homepage.description=Companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:6767 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
    network_mode: "service:gluetun"
  mylar3:
    image: lscr.io/linuxserver/mylar3
    container_name: recon-mylar3
    volumes:
      - ${VOL_RECON_MYLAR3_CONFIG:-~/container-data}/container-mounts/recon/mylar3/config:/config
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=Mylar
      - homepage.weight=70
      - homepage.icon=/dashboard-icons/png/mylar.png
      - homepage.href=http://recon.${TS_DOMAIN}:8090/
      - homepage.description=Comic Book downloader
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8090 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    network_mode: "service:gluetun"
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian
    container_name: recon-lazylibrarian
    environment:
      - TZ=America/Chicago
      - UMASK=022
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${VOL_RECON_LAZYLIBRARIAN_CONFIG:-~/container-data}/container-mounts/recon/lazylibrarian/config:/config
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=LazyLibrarian
      - homepage.weight=80
      - homepage.icon=/dashboard-icons/png/lazylibrarian.png
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:5299/
      - homepage.description=LazyLibrarian is a SickBeard, CouchPotato, Headphones-like application for ebooks, audiobooks and magazines
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:5299 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    network_mode: "service:gluetun"
  decluttarr:
    # https://github.com/ManiMatter/decluttarr?tab=readme-ov-file#running-in-docker
    image: ghcr.io/manimatter/decluttarr
    container_name: recon-decluttarr
    volumes:
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: INFO
      TEST_RUN: False
      TIMER: 10
      # IGNORED_DOWNLOAD_CLIENTS: >
      #   - emulerr
      # SSL_VERIFICATION: true
      # PRIVATE_TRACKER_HANDLING: "obsolete_tag"
      # PUBLIC_TRACKER_HANDLING: "remove"
      # OBSOLETE_TAG: "Obsolete"
      # PROTECTED_TAG: "Keep"

      # # --- Optional: Job Defaults ---
      # You can use these to set those parameters across all jobs. If you don't specify it here, the defaults set by system will be used
      # If you set job-specific parameters (further down below), they will override these settings.
      # max_strikes: 3
      # MIN_DAYS_BETWEEN_SEARCHES: 7
      # MAX_CONCURRENT_SEARCHES: 3

      # # --- Jobs (short notation) ---
      # If you want to go with the most basic settings, you can just turn them all on:
      # https://github.com/ManiMatter/decluttarr?tab=readme-ov-file#jobs
      REMOVE_BAD_FILES: True
      REMOVE_DONE_SEEDING: False
      REMOVE_FAILED_DOWNLOADS: False
      REMOVE_FAILED_IMPORTS: False
      REMOVE_METADATA_MISSING: True
      REMOVE_MISSING_FILES: True
      REMOVE_ORPHANS: False
      REMOVE_SLOW: False
      REMOVE_STALLED: True
      REMOVE_UNMONITORED: False
      SEARCH_BETTER: True
      SEARCH_MISSING: True
      DETECT_DELETIONS: True
      # --- Instances ---
      SONARR: >
        - base_url: "http://recon.$TS_DOMAIN:8989"
          api_key: "$SONARR_API_KEY"
      RADARR: >
        - base_url: "http://recon.$TS_DOMAIN:7878"
          api_key: "$RADARR_API_KEY"
      # READARR: >
      #   - base_url: "http://readarr:8787"
      #     api_key: "$READARR_API_KEY"
      # LIDARR: >
      #   - base_url: "http://lidarr:8686"
      #     api_key: "$LIDARR_API_KEY"
      # WHISPARR: >
      #   - base_url: "http://whisparr:6969"
      #     api_key: "$WHISPARR_API_KEY"
      # --- Download Clients ---
      QBITTORRENT: >
        - base_url: "http://recon.$TS_DOMAIN:8085"
      SABNZBD: >
        - base_url: "http://recon.$TS_DOMAIN:8086"
          api_key: "$SABNZBD_API_KEY"
    restart: on-failure
    depends_on:
      gluetun:
        condition: service_healthy
      sonarr:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
      sabnzbd:
        condition: service_healthy
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: recon-sabnzbd
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOL_RECON_SABNZBD_CONFIG:-~/container-data}/container-mounts/recon/sabnzbd/config:/config
      - ${VOL_RECON_DATA_MEDIA:-~/container-data}/container-mounts/recon/data/media:/media/arr
    labels:
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=SABnzbd
      - homepage.weight=22
      - homepage.icon=/dashboard-icons/svg/sabnzbd.svg
      - homepage.showstats=true
      - homepage.href=http://recon.${TS_DOMAIN}:8086/
      - homepage.description=The free and easy binary newsreader
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8086 || exit 1"
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
